name: free_flutter_core
description: Free Flutter Core contains helper classes/functions, themes, localization code, and other code that is used internally by the Free Flutter widgets. 
version: 1.0.0
homepage: https://github.com/cholojuanito/free_flutter_widgets/tree/master/packages/free_flutter_core

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  vector_math: ^2.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ">=1.9.0 <2.0.0"
  flutter_test:
    sdk: flutter

flutter:
