name: free_flutter_pdf
description: The Flutter PDF is a library for creating, reading, editing, and securing PDF files in Android, iOS, and web platforms.
version: 19.1.54-beta
homepage: https://github.com/cholojuanito/free_flutter_widgets/tree/main/packages/free_flutter_pdf

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ">=0.15.0 <0.20.0"
  xml: ">=4.5.1 <6.0.0"
  free_flutter_core:
    path: ../free_flutter_core
  crypto: ">=2.1.5 <4.0.0"
  convert: ">=1.0.0 <4.0.0"

